### ISSUE TITLE
Analyzse Stack trace: No unscramble checkbox option available

### ISSUE THREAD

**Issue by lgavSKOPOS** [Chimerapps/intellij-proguard-unscramble#1]
**Using Phpstorm IDE**

I am following a tutorial on jetbrains which seems to be up to date
Here is a link I am using to follow how to unscramble the stack trace:
https://www.jetbrains.com/help/idea/analyzing-external-stacktraces.html

**What I Expected:**
To find an Analyze optiion which contains Analyze Stack Trace.
Also to find an Unscramble option in the Analyze Stack Trace.

**What actually happens:**

- 1. Cannot find Analyze menu option. Analyze Stack Trace is under Tools menu.
- 2. Cannot see any unscramble option in Analyze Stack Trace.
- 3. Still had the issue after install Proguard Unscramble v1.0.0. 
             **Link to plugin:** https://plugins.jetbrains.com/plugin/11971-proguard-unscramble

**Tutorial I am following**
Here is a link I am using to follow how to unscramble.
https://www.jetbrains.com/help/idea/analyzing-external-stacktraces.html

**I have attached 3 pictures:**

- One of where I am seeing the Analyze Stack Trace option
![Screen Shot 2019-04-02 at 10 24 48](https://user-images.githubusercontent.com/47561153/55388642-f1353580-5533-11e9-88e9-e75b77dd381f.png)

- Second of what I get when I enter the set up Analyze Stack Trace
![Screen Shot 2019-04-02 at 10 26 53](https://user-images.githubusercontent.com/47561153/55388646-f3978f80-5533-11e9-9aa6-3bb4ccf10b1a.png)

- Third of what the output of the Analyze Stack Trace Option is
![Screen Shot 2019-04-02 at 10 29 30](https://user-images.githubusercontent.com/47561153/55388669-feeabb00-5533-11e9-8222-bd16a58f1911.png)

**What is wrong here?**

**Phpstorm version** I am using:
PhpStorm 2019.1
Build #PS-191.6183.95, built on March 27, 2019
Licensed to SKOPOS CONNECT GmbH / Luke Gavin
Subscription is active until February 25, 2020
JRE: 1.8.0_202-release-1483-b39 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6

**Comment by lgavSKOPOS** [comment]
@NicolaChimerapps Is this a problem that should be looked into or am I using this plugin incorrectly?

**Comment by NicolaVerbeeck** [comment]
Hi @lgavSKOPOS, this plugin is aimed specifically at java and android development. These 2 often use proguard as an obfuscation method which requires de-obfuscation based on compile time generated trace files. It seems that this de-obfuscation of stack traces is not something that is available in pystorm, perhaps because python is usually not obfuscated like java. 

In any case, this plugin needs to be installed using the plugin section of the intellij environment you are using. Via preferences -> plugins. When installed in an intellij flavor which supports unscrambling stack traces (such as intellij or android studio), the analyze stacktrace window will show you the option to use the plugin to unscramble the data.
